[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
required-features = ["cli"]

[dependencies]
crux_core.workspace = true
serde = { workspace = true, features = ["derive"] }
uniffi = "0.29.4"
uniffi-bindgen-cs = { git = "https://github.com/NordSecurity/uniffi-bindgen-cs", tag = "v0.10.0+v0.29.4" }
wasm-bindgen = "0.2.100"

[build-dependencies]
uniffi = { version = "0.29.4", features = ["build"] }

[features]
cli = ["uniffi/cli"]
typegen = ["crux_core/typegen"]
